"""empty message

Revision ID: 362928e561d6
Revises: 3b3475e96418
Create Date: 2024-03-21 16:32:48.826557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362928e561d6'
down_revision = '3b3475e96418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
